version: 0.2
 
phases:
  install:
    commands:
      - apt-get update -y
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Prepare JST locale
      - apt-get install build-essential
      - apt-get install openjdk-8-jdk
      - update-alternatives --config java
      - apt-get install -y tzdata
      - ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      - export TAG=`date "+%Y%m%d-%H%M"`
      - echo Prepare tag $TAG
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - make build
      - docker tag $IMAGE_REPO_NAME:test-$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:test-$TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:test-$TAG
      - echo Writing image definitions file...
